#ifndef DEVICE_GEN_CODE_SUBROUTINE_H_
#define DEVICE_GEN_CODE_SUBROUTINE_H_
void sgemm_NT_NT_m35_56_n9_9_k9_pps_47bd4ea(const float ** A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m53_56_n9_40_k35_nsp_41d708c(const float * __restrict__ A, int ExtraOffsetA, const float * B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m54_56_n9_40_k35_nsp_b4599dc(const float * __restrict__ A, int ExtraOffsetA, const float * B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m55_56_n9_40_k35_nsp_e7d889b(const float * __restrict__ A, int ExtraOffsetA, const float * B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_T_NT_m9_9_n9_9_k9_ppp_db79476(const float ** A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_T_m9_9_n9_9_k9_ppp_0c970c0(float fluxScale, const float ** A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m56_56_n6_56_k56_npp_87cf7c3(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m56_56_n6_56_k56_npp_da40531(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m21_24_n9_56_k56_nps_dd17eae(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m21_24_n9_9_k9_sps_899f278(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m56_56_n9_24_k21_nsp_41f2e57(const float * __restrict__ A, int ExtraOffsetA, const float * B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m21_24_n9_24_k21_nss_5830167(const float * __restrict__ A, int ExtraOffsetA, const float * B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void scopyAddScale_m56_56_n9_56_pp_88237f4(float Scale, const float ** A, int ExtraOffsetA, float ** B, int ExtraOffsetB, unsigned NumElements);
void scopyAddScale_m35_56_n9_56_pp_07aaceb(float Scale, const float ** A, int ExtraOffsetA, float ** B, int ExtraOffsetB, unsigned NumElements);
void scopyAddScale_m20_56_n9_56_pp_6eb2445(float Scale, const float ** A, int ExtraOffsetA, float ** B, int ExtraOffsetB, unsigned NumElements);
void scopyAddScale_m10_56_n9_56_pp_afcc802(float Scale, const float ** A, int ExtraOffsetA, float ** B, int ExtraOffsetB, unsigned NumElements);
void scopyAddScale_m4_56_n9_56_pp_c707c5f(float Scale, const float ** A, int ExtraOffsetA, float ** B, int ExtraOffsetB, unsigned NumElements);
void scopyAddScale_m1_56_n9_56_pp_96cca66(float Scale, const float ** A, int ExtraOffsetA, float ** B, int ExtraOffsetB, unsigned NumElements);
void sgemm_NT_NT_m35_40_n9_56_k53_nps_960fd76(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m35_40_n9_9_k9_spp_36989d0(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m35_40_n9_56_k54_nps_2269f5e(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m35_40_n9_9_k9_spp_9d7d789(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m35_40_n9_56_k55_nps_5d71d3c(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m20_40_n9_40_k32_nps_c33eb71(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m20_24_n9_9_k9_spp_0ba88dd(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m20_40_n9_40_k33_nps_c9310c2(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m20_24_n9_9_k9_spp_88ab2d4(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m20_40_n9_40_k34_nps_4344487(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m10_40_n9_24_k17_nps_41e96ee(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m10_16_n9_9_k9_spp_afbfa38(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m10_40_n9_24_k18_nps_20ec594(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m10_16_n9_9_k9_spp_fe81cdb(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m10_40_n9_24_k19_nps_277801b(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m4_40_n9_16_k7_nps_625feb0(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m4_8_n9_9_k9_spp_67deb58(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m4_40_n9_16_k8_nps_8f843c2(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m4_8_n9_9_k9_spp_784eae3(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m4_40_n9_16_k9_nps_d74565c(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m1_40_n9_8_k1_nps_2533254(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m1_8_n9_9_k9_spp_5c45fb8(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m1_40_n9_8_k2_nps_a20e3a8(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m1_8_n9_9_k9_spp_7cd43db(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m1_40_n9_8_k3_nps_cd5eaf9(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m49_56_n9_56_k56_nps_4ae838d(const float * __restrict__ A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m49_56_n9_9_k9_spp_539b719(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m49_56_n9_9_k9_spp_082a417(const float * A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m49_56_n9_9_k9_pps_834df01(const float ** A, int ExtraOffsetA, const float ** B, int ExtraOffsetB, float * C, int ExtraOffsetC, unsigned NumElements);
void sgemm_NT_NT_m56_56_n9_56_k49_nsp_572e194(const float * __restrict__ A, int ExtraOffsetA, const float * B, int ExtraOffsetB, float ** C, int ExtraOffsetC, unsigned NumElements);
#endif
